def get_features(data):
    features_target_lst = ["SK_ID_CURR",
                           'EXT_SOURCE_3',
                           'EXT_SOURCE_2',
                           'EXT_SOURCE_1',
                           'CC_CNT_DRAWINGS_ATM_CURRENT_MEAN',
                           'CC_CNT_DRAWINGS_CURRENT_MAX',
                           'BURO_DAYS_CREDIT_MEAN',
                           'CC_AMT_BALANCE_MEAN',
                           'CC_CNT_DRAWINGS_CURRENT_MEAN',
                           'BURO_MONTHS_BALANCE_SIZE_MEAN',
                           'BURO_CREDIT_ACTIVE_Closed_MEAN',
                           'DAYS_BIRTH',
                           'PREV_NAME_CONTRACT_STATUS_Refused_MEAN',
                           'BURO_CREDIT_ACTIVE_Active_MEAN',
                           'BURO_DAYS_CREDIT_MIN',
                           'DAYS_EMPLOYED',
                           'PREV_CODE_REJECT_REASON_XAP_MEAN',
                           'BURO_DAYS_CREDIT_UPDATE_MEAN',
                           'CC_AMT_BALANCE_MAX',
                           'DAYS_EMPLOYED_PERC',
                           'ACTIVE_MONTHS_BALANCE_SIZE_MEAN',
                           'REFUSED_DAYS_DECISION_MAX',
                           'CC_AMT_BALANCE_MIN',
                           'ACTIVE_DAYS_CREDIT_MEAN',
                           'CC_CNT_DRAWINGS_ATM_CURRENT_MAX',
                           'PREV_NAME_CONTRACT_STATUS_Approved_MEAN',
                           'CC_CNT_DRAWINGS_CURRENT_VAR',
                           'CC_MONTHS_BALANCE_MIN',
                           'BURO_STATUS_1_MEAN_MEAN',
                           'CC_CNT_DRAWINGS_ATM_CURRENT_VAR',
                           'ACTIVE_DAYS_CREDIT_MAX']
    return features_target_lst
